import { CHAPTERS, LEVEL_COUNT, LEVELS_PER_CHAPTER, getLevel } from './levels.js';
import { totalStars, completed, dayKey, MISSIONS, TOOLS, chapterComplete } from './progress.js';
import { art } from './art.js';
export const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const fmt=n=>Number(n||0).toLocaleString('ru-RU');
export const icon=art;
export const stars=(n,cls='stars-inline')=>`<span class="${cls}" aria-label="${n} из 3 звёзд">${[1,2,3].map(i=>icon('star',i>n?'empty':'')).join('')}</span>`;
export const NAMES={blue:'Синий щит',green:'Зелёный лист',red:'Красная книга',orange:'Оранжевая плитка',yellow:'Золотая корона',purple:'Фиолетовый кристалл',ice:'Лёд',crate:'Ящик',stone:'Камень',grass:'Трава',chain:'Цепь','rocket-h':'Ракета по горизонтали','rocket-v':'Ракета по вертикали',orb:'Радужный шар',bomb:'Бомба'};
export const TOOL_INFO={hammer:'Убирает фишку или один слой препятствия.',row:'Очищает выбранную строку.',column:'Очищает выбранный столбец.',shuffle:'Меняет фишки местами. Сохраняет бонусы.','rocket-h':'Ракета на старте уровня.',bomb:'Бомба на старте уровня.',orb:'Радужный шар на старте уровня.'};
export const NAV=[['map','map','Карта'],['rewards','chest','Награды'],['records','trophy','Рекорды'],['shop','hammer','Бустеры'],['rules','orb','Как играть']];
export function navigation(active,p){return NAV.map(([page,name,label])=>`<button data-action="nav" data-page="${page}" class="${active===page?'active':''}" ${active===page?'aria-current="page"':''}>${icon(name)}<span>${label}</span>${page==='rewards'&&p.daily.lastClaim!==dayKey()?'<i class="nav-dot"></i>':''}</button>`).join('');}
export const heading=(eyebrow,title,subtitle)=>`<header class="page-heading"><div class="eyebrow">${eyebrow}</div><h1>${title}</h1><p>${subtitle}</p></header>`;
export function homePage(p){
  return `<div class="home-menu">${art('logo','home-logo')}<div class="home-actions">${p.active?`<button class="primary" data-action="resume-saved">Продолжить</button>`:''}<button class="primary" data-action="level" data-id="${p.unlocked}">Уровень ${p.unlocked}</button><button class="primary blue-button" data-action="nav" data-page="map">Карта уровней</button><button class="primary orange-button" data-action="nav" data-page="rewards">Награды</button></div><div class="home-icons"><button class="art-button" data-action="settings" aria-label="Настройки">${art('settings')}</button><button class="art-button" data-action="rules" aria-label="Правила">${art('rules')}</button><button class="art-button" data-action="nav" data-page="records" aria-label="Рекорды">${art('trophy')}</button></div></div>`;
}
export const goalList=goals=>Object.entries(goals).map(([k,v])=>`<div title="${NAMES[k]}" aria-label="${NAMES[k]}: ${v}">${icon(k)}<b>${v}</b></div>`).join('');
export function mapPage(p,chapter){
  const chapterInfo=CHAPTERS[chapter],start=chapter*20+1,pts=[];
  const nodes=Array.from({length:20},(_,i)=>{
    const id=start+i,x=50+Math.sin(i*1.24)*24,y=1845-i*88,record=p.levels[id],locked=id>p.unlocked,current=id===p.unlocked;
    pts.push([x*4,y]);
    return `<button class="level-node ${locked?'locked':record?.stars?'done':''} ${current?'current':''} ${id%5===0?'hard':''}" style="left:${x}%;top:${y}px" data-action="level" data-id="${id}" aria-label="Уровень ${id}${locked?', закрыт':record?.stars?`, ${record.stars} звезды`:''}" ${locked?'aria-disabled="true"':''}>${locked?icon('lock'):id}${record?.stars?stars(record.stars,'node-stars'):''}${current?'<span class="node-label">ВАШ СЛЕДУЮЩИЙ ШАГ</span>':''}</button>`;
  }).join('');
  const path=pts.map(([x,y],i)=>i?`C ${pts[i-1][0]} ${y+44}, ${x} ${y+44}, ${x} ${y}`:`M ${x} ${y}`).join(' ');
  const count=totalStars(p),target=(p.claimedChests+1)*30,ready=count>=target;
  return `<div class="map-page">${heading(`ГЛАВА ${chapter+1} ИЗ 25`,chapterInfo.name,chapterInfo.subtitle)}${p.active?`<div class="resume-banner"><span>Ваше незавершённое приключение сохранено</span><button data-action="resume-saved">Продолжить</button></div>`:''}
  <div class="map-layout"><div class="map-card"><div class="chapter-header"><button data-action="chapter" data-delta="-1" aria-label="Предыдущая глава" ${chapter===0?'disabled':''}>‹</button><div><small>ПУТЬ ИСКАТЕЛЯ ЧУДЕС</small><strong>Уровни ${start}–${start+19}</strong></div><button data-action="chapter" data-delta="1" aria-label="Следующая глава" ${chapter===24?'disabled':''}>›</button></div>
  <div class="map-scroll" id="map-scroll"><div class="map-landscape"><svg class="map-route" viewBox="0 0 400 1950" preserveAspectRatio="none" aria-hidden="true"><path d="${path}" fill="none" stroke="#64814955" stroke-width="34" stroke-linecap="round" transform="translate(0 5)"/><path d="${path}" fill="none" stroke="#f5e6b3" stroke-width="30" stroke-linecap="round"/><path d="${path}" fill="none" stroke="#fff5ce" stroke-width="20" stroke-linecap="round" stroke-dasharray="2 9"/></svg><div class="map-finish">${icon('chest')}<span>Награда за главу</span></div>${nodes}</div></div>
  <div class="map-play"><button class="primary" data-action="level" data-id="${p.unlocked}">Играть <span>·</span> Уровень ${p.unlocked} <span>›</span></button></div></div>
  <aside class="map-side"><div class="feature-card"><div class="feature-top">${icon('chest')}<div><h3>Звёздный сундук</h3><p>Собирайте звёзды —<br>открывайте подарки</p></div></div><div class="progress-track"><i style="width:${Math.min(100,(count-p.claimedChests*30)/30*100)}%"></i></div><div class="progress-text"><span>До нового сундука</span><b>${Math.min(30,count-p.claimedChests*30)} / 30 ★</b></div><button class="secondary" data-action="${ready?'chest':'nav'}" data-page="rewards">${ready?'Открыть сундук':'Посмотреть награды'}</button></div>
  <div class="feature-card daily-card"><div class="feature-top">${icon('orb')}<div><h3>Испытание дня</h3><p>Новая головоломка.<br>200 монет за победу.</p></div></div><button class="secondary" data-action="daily-level">${p.daily.challengeDate===dayKey()?'Улучшить результат':'Принять вызов'}</button></div>
  <div class="feature-card"><div class="feature-top">${icon('coin')}<div><h3>Подарок на сегодня</h3><p>Монеты и инструмент<br>каждый день</p></div></div><button class="secondary" data-action="${p.daily.lastClaim===dayKey()?'nav':'daily-gift'}" data-page="rewards">${p.daily.lastClaim===dayKey()?'Подарок получен ✓':'Забрать подарок'}</button></div><div class="chapter-note">${icon('star')}<span>Переигрывайте уровни,<br>чтобы собрать все три звезды.</span></div></aside></div></div>`;
}
export function recordsPage(p,tab='campaign',chapter=0){
  const stats=p.stats;
  let content='';
  if(tab==='campaign'){
    const rows=Array.from({length:20},(_,i)=>chapter*20+i+1).filter(id=>p.levels[id]?.stars>0).map(id=>{const r=p.levels[id],l=getLevel(id);return `<div class="record-row"><div class="record-level">Уровень ${id}<small>${esc(l.name)}</small></div>${stars(r.stars)}<b>${fmt(r.score)}</b><button class="tiny-play" data-action="level" data-id="${id}" aria-label="Переиграть уровень ${id}">▶</button></div>`;}).join('');
    content=`<div class="table-card"><div class="table-toolbar"><h3>Мои лучшие результаты</h3><select id="records-chapter" aria-label="Глава рекордов">${CHAPTERS.map((c,i)=>`<option value="${i}" ${i===chapter?'selected':''}>${i+1}. ${c.name}</option>`).join('')}</select></div><div class="record-row head"><span>УРОВЕНЬ</span><span>ЗВЁЗДЫ</span><span>ОЧКИ</span><span></span></div>${rows||`<div class="empty-state">${icon('trophy')}<h3>Ваша история ещё впереди</h3><p>Пройдите первый уровень этой главы. Здесь появятся ваши звёзды и лучшие результаты.</p></div>`}</div><p class="notice">Личные рекорды хранятся на этом устройстве${p.cloud?' и синхронизируются с VK':''}. Повторная победа улучшает результат; награда за первое прохождение выдаётся один раз.</p>`;
  }else if(tab==='arcade')content=`<div class="arcade-grid">${[['wall','crate','Стена','Убирайте ящики. Каждые 5 ходов стена поднимается. Не дайте ей достичь верхнего края.'],['endless','orb','Бесконечность','Выполняйте цели одной волны за другой. Очки суммируются, ходы обновляются.']].map(([m,i,n,d])=>`<div class="arcade-card">${icon(i)}<h3>${n}</h3><p>${d}</p><div class="record">${fmt(stats[m])}<small>ЛИЧНЫЙ РЕКОРД</small></div><button class="primary" data-action="arcade" data-mode="${m}">Играть</button></div>`).join('')}</div>`;
  else content=`<div class="table-card">${[['Всего начато игр',stats.games],['Побед',stats.wins],['Собрано фишек',stats.collected],['Создано бонусов',stats.powers],['Лучшая цепочка каскадов',stats.bestCascade],['Рекорд испытания сегодня',p.daily.challengeDate===dayKey()?p.daily.challengeScore:0]].map(([n,v])=>`<div class="table-toolbar"><h3>${n}</h3><b>${fmt(v)}</b></div>`).join('')}</div>`;
  return heading('КАЖДАЯ ПОБЕДА ВАЖНА','Зал достижений','Ваши звёзды, лучшие комбинации и личные рекорды.')+`<div class="content-pad"><div class="stats-grid">${[['trophy',completed(p),'уровней пройдено'],['star',totalStars(p),'звёзд собрано'],['bomb',stats.bestCascade,'лучший каскад']].map(([i,v,n])=>`<div class="stat-card">${icon(i)}<strong>${fmt(v)}</strong><small>${n}</small></div>`).join('')}</div><div class="tab-strip">${[['campaign','Уровни'],['arcade','Аркады'],['stats','Статистика']].map(([k,n])=>`<button class="${tab===k?'active':''}" data-action="records-tab" data-tab="${k}">${n}</button>`).join('')}</div>${content}</div>`;
}
export function shopPage(p){return heading('МАЛЕНЬКАЯ ПОМОЩЬ ДЛЯ БОЛЬШИХ ПОБЕД','Мастерская бустеров','Покупайте инструменты за монеты, заработанные в игре.')+`<div class="content-pad">${[['Во время игры',['hammer','row','column','shuffle']],['На старт уровня',['rocket-h','bomb','orb']]].map(([title,keys])=>`<h2 class="section-label">${title}<small>${title==='Во время игры'?'Без расхода хода':'Выберите перед началом'}</small></h2><div class="shop-grid">${keys.map(k=>`<article class="shop-item">${icon(k)}<h3>${TOOLS[k].name}</h3><p>${TOOL_INFO[k]}</p><div class="owned">В запасе: ${p.inventory[k]}</div><button class="price-button" data-action="buy" data-tool="${k}" ${p.coins<TOOLS[k].price?'disabled':''} aria-label="Купить ${TOOLS[k].name} за ${TOOLS[k].price} монет">${icon('coin')}${TOOLS[k].price}<span>+1</span></button></article>`).join('')}</div>`).join('')}<p class="notice">Бустеры также выпадают из сундуков, ежедневных подарков и заданий. Все покупки здесь — за игровые монеты.</p></div>`;}
export function rewardsPage(p){
  const today=dayKey(),claimed=p.daily.lastClaim===today,streak=p.daily.streak||0,starCount=totalStars(p);
  return heading('ЕЩЁ ОДИН ПОВОД ДЛЯ ЧУДА','Подарки и открытия','Новая цель каждый день. Большая награда за каждый этап.')+`<div class="content-pad"><div class="daily-banner">${icon('orb')}<div><div class="eyebrow" style="color:#e6cda3">${today.split('-').reverse().join('.')}</div><h2>Испытание дня</h2><p>Одна головоломка на весь день.<br>За первую победу: 200 монет и молоток.</p><button class="secondary" data-action="daily-level">${p.daily.challengeDate===today?'Сыграть ещё раз':'Начать испытание'} ›</button></div></div>
  <div class="feature-card"><h3>Семь дней подарков</h3><p>Заходите за монетами и бустерами. На седьмой день — радужный шар.</p><div class="daily-days">${Array.from({length:7},(_,i)=>`<div class="day ${i<streak&&claimed?'claimed':''} ${i===(claimed?streak-1:streak%7)?'current':''}"><small>День ${i+1}</small>${icon(i===6?'orb':(i+1)%3===0?'bomb':'hammer')}<b>${80+i*20} ${i<streak&&claimed?'✓':'монет'}</b></div>`).join('')}</div><button class="primary gold-button" data-action="daily-gift" ${claimed?'disabled':''}>${claimed?'Подарок получен · до завтра':'Забрать подарок'}</button></div>
  <h2 class="section-label">Сегодня получится! <small>Обновление в полночь</small></h2>${MISSIONS.map(m=>{const done=p.missions.claimed.includes(m.key),n=p.missions[m.key];return `<div class="mission">${icon(m.tool)}<div class="mission-copy"><h3>${m.name}</h3><small>${Math.min(n,m.goal)} / ${m.goal} · ${m.coins} монет + бустер</small><div class="progress-track"><i style="width:${Math.min(100,n/m.goal*100)}%"></i></div></div><button class="secondary" data-action="mission" data-key="${m.key}" ${done||n<m.goal?'disabled':''}>${done?'Получено ✓':'Забрать'}</button></div>`;}).join('')}
  <h2 class="section-label">Звёздный сундук ${icon('star')}</h2><div class="feature-card"><div class="feature-top">${icon('chest')}<div><h3>30 звёзд — новое сокровище</h3><p>250 монет, радужный шар и молоток.</p></div></div><div class="progress-track"><i style="width:${Math.min(100,(starCount-p.claimedChests*30)/30*100)}%"></i></div><div class="progress-text"><span>Собрано для следующего сундука</span><b>${Math.min(30,starCount-p.claimedChests*30)} / 30</b></div><button class="secondary" data-action="chest" ${starCount<(p.claimedChests+1)*30?'disabled':''}>Открыть сундук</button></div>
  <h2 class="section-label">Главы вашей истории <small>25 приключений</small></h2><div class="chapter-rewards">${CHAPTERS.map((c,i)=>{const done=p.claimedChapters.includes(i),count=Array.from({length:20},(_,j)=>i*20+j+1).filter(id=>p.levels[id]?.stars).length;return `<div class="chapter-reward"><h3>${i+1}. ${c.name}</h3><p>${count} / 20 уровней · 400 монет и 3 бустера</p><div class="progress-track"><i style="width:${count*5}%"></i></div><button class="secondary" data-action="chapter-reward" data-id="${i}" ${done||!chapterComplete(p,i)?'disabled':''}>${done?'Получено ✓':'Забрать награду'}</button></div>`;}).join('')}</div></div>`;
}
export const RULE_TABS=[['basics','Основы'],['powers','Бонусы'],['obstacles','Препятствия'],['combos','Комбинации']];
const rules={
  basics:[['map','Цели важнее очков','Соберите все цели до окончания ходов. Цифры над полем показывают, сколько осталось. Оставшиеся цели отмечаются галочкой после выполнения.'],['blue','Один красивый ход','Проведите фишку к соседней или нажмите на две соседние фишки. Соберите 3 одинаковые в ряд. Обмен без комбинации возвращается назад и не тратит ход.'],['star','Три звезды за мастерство','Победа даёт 1 звезду. Сохраните не менее 12% начальных ходов для 2 звёзд и 28% для 3. Переигрывание улучшает рекорд.'],['hammer','Помощь всегда рядом','Молоток, стрела, пушка и перемешивание не тратят ход. Нажмите инструмент, затем клетку. Повторное нажатие отменяет выбор.'],['shuffle','Если ходов на поле нет','Игра бесплатно перемешает фишки. Препятствия, трава, цепи и созданные бонусы сохранятся.'],['heart','Играйте в своём темпе','Здесь нет ожидания жизней. Пауза и закрытие страницы сохраняют незавершённую игру. Стрелки и Enter позволяют играть с клавиатуры.']],
  powers:[['rocket-h','Ракета · 4 в ряд','Четыре одинаковые фишки по горизонтали создают горизонтальную ракету, по вертикали — вертикальную. Ракета очищает всю линию.'],['bomb','Бомба · Т или Г','Пересечение двух рядов из одинаковых фишек создаёт бомбу. Взрыв очищает область 5 × 5 вокруг неё.'],['orb','Радужный шар · 5 в ряд','Пять одинаковых в прямую линию создают шар. Обменяйте его с цветной фишкой, чтобы убрать этот цвет. При нажатии выбирается самый частый цвет.'],['rocket-v','Активация в одно касание','Нажмите на бонус или обменяйте его с соседней фишкой. Активация тратит один ход. Попавшие под взрыв бонусы запускают цепную реакцию.']],
  obstacles:[['crate','Ящики · с уровня 3','Комбинация вплотную или взрыв снимают один слой. Ящик не двигается. Точки в углу показывают оставшиеся слои.'],['ice','Лёд · с уровня 11','Лёд занимает отдельную клетку и стоит на месте. Комбинация рядом или взрыв снимают слой. Цель засчитывается только после полного разрушения.'],['grass','Трава · с уровня 14','Соберите комбинацию на траве или попадите по ней бонусом. Трава остаётся в клетке, когда фишки меняются местами.'],['stone','Камни · с уровня 21','Соседние комбинации не повреждают камень. Используйте ракеты, бомбы или инструменты. Один удар снимает один слой.'],['chain','Цепи · с уровня 61','Фишка в цепи не двигается, не падает и не участвует в комбинациях. Взрыв или инструмент снимает цепь и оставляет фишку на поле.'],['bomb','Слои и каскады','Пересекающиеся взрывы в одной волне снимают один слой. Следующая комбинация после падения — новая волна и ещё один удар. Под неподвижными препятствиями фишки появляются в отдельных секциях.']],
  combos:[['rocket-h','Ракета + ракета','Очищают одну строку и один столбец крестом.','rocket-v'],['bomb','Ракета + бомба','Очищают три строки и три столбца.','rocket-h'],['bomb','Бомба + бомба','Большой взрыв: область 9 × 9 вокруг комбинации.','bomb'],['orb','Шар + любой бонус','Все свободные фишки самого частого цвета превращаются в этот бонус и активируются.','rocket-h'],['orb','Шар + шар','Очищают всё поле и снимают один слой с каждого препятствия.','orb']],
};
export function rulesContent(tab='basics') {return `<div class="rules-grid">${rules[tab].map(([i,title,body,second])=>`<article class="rule-card">${second?`<div class="combo-pair">${icon(i)}<b>+</b>${icon(second)}</div>`:icon(i)}<h3>${title}</h3><p>${body}</p></article>`).join('')}</div>`;}
export function rulesPage(tab){return heading('ПРОСТО НАЧАТЬ. ИНТЕРЕСНО ОСВАИВАТЬ.','Искусство комбинаций','Маленькие секреты, которые делают каждый ход сильнее.')+`<div class="content-pad"><div class="tab-strip">${RULE_TABS.map(([k,n])=>`<button class="${tab===k?'active':''}" data-action="rules-tab" data-tab="${k}">${n}</button>`).join('')}</div>${rulesContent(tab)}</div>`;}
